debug = True
action_after_time_default = [0, 10]
action_after_time_minimum = [00, 1]
applicatin_show_name = 'RemoteControlPc'
shelve_file_name = 'conf'
log_name = 'app.log'
logger_backup_count = 3
logger_max_bytes = 1024 * 512
web_site = 'http://google.com'
api_base_url = 'http://google.com'
